name: Main and pull request checks
on:
  push:
    branches: [ 'main', 'version.*' ]
  pull_request:
    branches: [ 'main', 'version.*' ]
jobs:
  assemble:
    strategy:
      fail-fast: false
      matrix:
        java-version: [17, 21]
        runs-on: [ubuntu-latest]
    name: Assemble on ${{ matrix.runs-on }} with JDK ${{ matrix.java-version }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: gradle
      - name: Assemble with Gradle
        run: ./gradlew assemble

  check:
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { opensearch-version: 1.3.18, java-version: 17 }
          - { opensearch-version: 1.3.18, java-version: 21 }
          - { opensearch-version: 2.11.0, java-version: 17 }
          - { opensearch-version: 2.11.0, java-version: 21 }
          - { opensearch-version: 2.18.0, java-version: 17 }
          - { opensearch-version: 2.18.0, java-version: 21 }
          - { opensearch-version: 2.18.0, java-version: 23 }
        runs-on: [ubuntu-latest]
    name: Check on ${{ matrix.runs-on }} with JDK ${{ matrix.entry.java-version }} against OpenSearch ${{ matrix.entry.opensearch-version }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.entry.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.entry.java-version }}
          distribution: 'temurin'
          cache: gradle
      - name: Check with Gradle
        run: ./gradlew check -Psde.testcontainers.image-version=${{ matrix.entry.opensearch-version }}
